import type { Customer, PlannedOffer, RealizationScenario } from '../../types';

export const buildInternalAnalysisReport = (
  offer: PlannedOffer,
  customer?: Customer,
  scenario?: RealizationScenario,
) => ({
  reportType: 'internal_analysis' as const,
  classification: 'ŞİRKET İÇİ / GİZLİ' as const,
  customer: { id: customer?.id ?? offer.customerId, name: customer?.name ?? 'Müşteri' },
  offer: {
    id: offer.id,
    title: offer.title,
    version: offer.version,
    policyVersion: offer.resultSnapshot.policyVersion,
    calculatedAt: offer.resultSnapshot.calculatedAt,
    stateSnapshot: structuredClone(offer.stateSnapshot),
    marketPriceSnapshot: structuredClone(offer.resultSnapshot.marketPriceSnapshot ?? []),
    tariffSnapshots: offer.resultSnapshot.periods.map((period) => period.tariffSnapshot),
  },
  financials: {
    offerMargin: offer.resultSnapshot.totals.offerMargin,
    imbalance: offer.resultSnapshot.totals.imbalanceAmount,
    piu: offer.resultSnapshot.totals.piuAmount,
    paymentChannelCost: offer.resultSnapshot.totals.paymentChannelCost,
    creditCost: offer.resultSnapshot.totals.creditCost,
    valorIncome: offer.resultSnapshot.totals.valorIncome,
    excessProductionPurchase: offer.resultSnapshot.totals.excessProductionPurchase,
    netProfit: scenario?.resultSnapshot.actualProfit ?? offer.resultSnapshot.totals.netProfit,
    profitPerMwh: offer.resultSnapshot.totals.profitPerMwh,
    breakevenOfferRate: offer.resultSnapshot.totals.breakevenOfferRate,
    openFinancingBalance:
      scenario?.resultSnapshot.openFinancingBalance ?? offer.resultSnapshot.openFinancingBalance,
    customerAdvance:
      scenario?.resultSnapshot.receivableLedger.customerAdvance ??
      offer.resultSnapshot.endingCustomerAdvance ??
      0,
    openReceivable:
      scenario?.resultSnapshot.endingOpenReceivable ?? offer.resultSnapshot.endingOpenReceivable ?? 0,
  },
  reconciliationInstructions: structuredClone(offer.resultSnapshot.reconciliationInstructions ?? []),
  profitLedger: structuredClone(scenario?.resultSnapshot.profitLedger ?? offer.resultSnapshot.profitLedger),
  monthlyProfit: structuredClone(scenario?.resultSnapshot.monthlyProfit ?? offer.resultSnapshot.monthlyProfit),
  lateFee: scenario
    ? {
        amount: scenario.resultSnapshot.totalLateFee,
        vat: scenario.resultSnapshot.totalLateFeeVat,
        documents: structuredClone(scenario.resultSnapshot.lateFeeDocuments),
      }
    : undefined,
  warnings: [
    ...offer.resultSnapshot.warnings,
    ...(scenario?.resultSnapshot.marketPriceWarnings ?? []),
  ],
});

export type InternalAnalysisReportModel = ReturnType<typeof buildInternalAnalysisReport>;

export const internalAnalysisReportRows = (report: InternalAnalysisReportModel): unknown[][] => [
  ['K2 EnerjiPro 3.0 — İç Finansal Analiz'],
  [report.classification],
  ['Müşteri', report.customer.name],
  ['Teklif', report.offer.title],
  ['Versiyon', report.offer.version],
  ['Politika', report.offer.policyVersion],
  ['Snapshot tarihi', report.offer.calculatedAt],
  ['Teklif state snapshot', JSON.stringify(report.offer.stateSnapshot)],
  ['Teklif marjı', report.financials.offerMargin],
  ['Dengesizlik', report.financials.imbalance],
  ['PİÜ', report.financials.piu],
  ['Kanal maliyeti', report.financials.paymentChannelCost],
  ['Kredi maliyeti', report.financials.creditCost],
  ['Valör geliri', report.financials.valorIncome],
  ['GES ihtiyaç fazlası', report.financials.excessProductionPurchase],
  ['Net kâr', report.financials.netProfit],
  ['Birim kâr', report.financials.profitPerMwh],
  ['Başabaş oranı', report.financials.breakevenOfferRate],
  ['Açık finansman bakiyesi', report.financials.openFinancingBalance],
  ['Müşteri avansı', report.financials.customerAdvance],
  ['Açık alacak', report.financials.openReceivable],
  [],
  ['Piyasa fiyat snapshot'],
  ['Ay', 'PTF', 'PTF kaynağı', 'YEKDEM', 'YEKDEM kaynağı'],
  ...report.offer.marketPriceSnapshot.map((item) => [
    item.month,
    item.ptfUnitPrice,
    item.ptfPriceSource,
    item.yekdemUnitPrice,
    item.yekdemPriceSource,
  ]),
  [],
  ['Tarife snapshot'],
  ['Dönem', 'Tarife id', 'Versiyon', 'Geçerlilik', 'KDV', 'BTV', 'Dağıtım', 'Kaynak', 'Manuel override', 'Override nedeni'],
  ...report.offer.tariffSnapshots.map((item, index) => [
    index + 1,
    item?.tariffId ?? 'legacy',
    item?.versionLabel ?? 'metadata yok',
    item ? `${item.validFrom ?? '—'} / ${item.validTo ?? 'açık'}` : 'legacy snapshot',
    item?.kdvRate,
    item?.btvRate,
    item?.distributionUnitTlMwh,
    item?.sourceLabel ?? 'Legacy snapshot',
    item?.manualOverride ? 'Evet' : 'Hayır',
    item?.overrideReason ?? '',
  ]),
  [],
  ['Mutabakat türü', 'Dönem', 'Tutar', 'Tarih', 'Not'],
  ...report.reconciliationInstructions.map((item) => [
    item.type,
    item.periodId,
    item.amount,
    item.scheduledDate ?? item.referenceDate,
    item.note,
  ]),
  [],
  ['Profit ledger'],
  ['Ay', 'Bileşen', 'Yön', 'Tutar', 'Not'],
  ...report.profitLedger.map((item) => [
    item.economicMonth,
    item.component,
    item.direction,
    item.amount,
    item.note ?? '',
  ]),
  [],
  ['Aylık tahakkuk ve nakit'],
  ['Ay', 'Tahakkuk kârı', 'Nakit girişi', 'Nakit çıkışı', 'Nakit sonucu', 'Mutabakat farkı'],
  ...report.monthlyProfit.map((item) => [
    item.month,
    item.accrualProfit,
    item.cashInflows,
    item.cashOutflows,
    item.cashResult,
    item.reconciliationDifference,
  ]),
  [],
  ['Gecikme bedeli', report.lateFee?.amount ?? 0],
  ['Gecikme KDV’si', report.lateFee?.vat ?? 0],
  ['Gecikme belge sayısı', report.lateFee?.documents.length ?? 0],
  [],
  ['Uyarılar'],
  ...report.warnings.map((warning) => [warning]),
];
